# Generated by Django 5.0.6 on 2024-07-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
